config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  root to: "posts#index"

  get "/posts/:id/destroy" => "posts#destroy"

  resources :posts, except: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, {presence: true}
  validates :body, {presence: true}
  validates :user_id, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, :except=>[:index, :show]
before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def index
    @posts = Post.all.order(created_at: :desc)
    ids = REDIS.zrevrange "posts/daily/#{Date.today.to_s}", 0, 2
    @hi_posts = Post.where(id: ids)
    # today = Date.today.to_s
    # @daily_pageviews = Hash.new
    #   @posts.each do |post|
    #   @daily_pageviews[post.id] = REDIS.get "posts/daily/#{today}/#{post.id}"
    #   end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(create_params)
    if @post.save
      redirect_to("/")
    else
      render("/posts/new")
    end
  end


  def show
    @post = Post.find_by(id: params[:id])
    REDIS.zincrby "posts/daily/#{Date.today.to_s}", 1, "#{@post.id}"
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id:params[:id])
    if @post.update(params.require(:post).permit(:title, :body))
      redirect_to("/")
    else
      render("/posts/#{post.id}/edit")
    end
  end

  def destroy
    @post = Post.find_by(id:params[:id])
    @post.destroy
    redirect_to("/")
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/")
    end
  end

  private
    def create_params
      params.require(:post).permit(:title, :body).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head lang="ja">
        <meta charset="UTF-8">
        <title>Rails Camp Blog</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <!-- <stylesheet_link_tag "application" type="text.css" media="screen"> -->
    </head>

  <body>

    <header>
        <p id="logo"><a href="/posts">RailsCamp<span>Blog</span></a></p>
          <div id="nav">
            <ul>
              <% if user_signed_in? %>
                <li><a href="/posts">トップ</a></li>
                <li><a href="/posts/new">新規投稿</a></li>
                <li><a href="/users/sign_out">ログアウト</a></li>
              <% else %>
                <li><a href="/users/sign_in">ログイン</a></li>
                <li><a href="/users/sign_up">新規登録</a></li>
                <div class="clear"></div>
              <% end %>
            </ul>
          </div>
        <div class="clear"></div>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for(@post, url: post_path) do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :body %>
    <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<body>

<div id="main">
    <img src="main-img.jpg">
</div>


<div id="article_wrap">

    <div id="article_list">

        <div>
          <% @posts.each do |post| %>
            <h2>
              <div class="title">
                <%= link_to("#{post.title}","/posts/#{post.id}") %>
                <p><%= post.updated_at %><%= post.user_id %></p>
              </div>
            </h2>
              <% if current_user.id == post.user_id %>
                  <%= link_to("編集","/posts/#{post.id}/edit") %>
                  <%= link_to("削除", "/posts/#{post.id}/destroy", method: :delete) %>
              <% end %>
          <% end %>
        </div>
    </div>

    <div id="sidebar">

        <h2>★PV数ランキング</h2>
        <ul>
          <% @hi_posts.each do |hi_post| %>
            <li><%= link_to("#{hi_post.title}","/posts/#{hi_post.id}") %><span></span></li>
          <% end %>
        </ul>
    </div>
    <div class="clear"></div>


<footer>
    <div id="footer_inner">
        <p>Copyright RailsCamp 2015 All Rights Reserved</p>
    </div>
</footer>

</body>
</html>

app/views/posts/new.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<%= form_for(@post,url: posts_path) do |f|  %>
<div class="form">
    <%= f.text_field :title %>
    <%= f.text_area :body %>
    <%= f.submit "送信" %>
</div>
<% end %>

app/views/posts/show.html.erb
<div id="title">
    <div>
        <p><h1><%= @post.title %></h1></p>
    </div>
</div>

<div id="article_wrap">

    <div id="content">

      <h2><%= @post.body %></h2>

    </div>
</div>